# Generated by Django 5.1.5 on 2025-01-20 15:04

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('price', models.BigIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=27)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('type_user', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee')], max_length=25)),
                ('courses', models.ManyToManyField(blank=True, related_name='users', to='fingerprints.course')),
            ],
        ),
    ]
