# Generated by Django 5.1.5 on 2025-01-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
