# Generated by Django 5.1.5 on 2025-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0003_customuser_description_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='telegram_group_id',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
    ]
