# Generated by Django 5.1.5 on 2025-01-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0004_course_telegram_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Aliyev Samir', max_length=255),
            preserve_default=False,
        ),
    ]
