# Generated by Django 5.1.5 on 2025-02-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0007_rename_attendances_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
