# Generated by Django 5.1.5 on 2025-02-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0008_remove_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(),
        ),
    ]
