# Generated by Django 5.1.5 on 2025-02-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0009_alter_attendance_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='person',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fingerprints.customuser'),
            preserve_default=False,
        ),
    ]
